pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - status-success=gruckion.mergify-azure-pipeline-example
      - base=master
    actions:
      merge:
        method: merge
        strict: "smart"
      delete_head_branch: {}
