pull_request_rules:
  - name: Automatic merge
    conditions:
      - status-sucess=gruckion.mergify-azure-pipeline-example
    actions:
      merge:
        method: squash
        strict: "smart"
      delete_head_branch: {}